# Generated by Django 4.2 on 2023-05-02 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_child_name_alter_app_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='parent_2',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='name',
            name='child_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
