# Generated by Django 4.2 on 2023-05-03 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0008_remove_name_child_id_alter_child_parent_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='name',
            name='custom',
        ),
        migrations.AlterField(
            model_name='name',
            name='popularity',
            field=models.BigIntegerField(default=None, null=True),
        ),
    ]
