# Generated by Django 4.2 on 2023-05-04 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0009_remove_name_custom_alter_name_popularity'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='gender',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='app_user',
            name='email',
            field=models.EmailField(max_length=150, unique=True),
        ),
    ]
