# Generated by Django 4.2 on 2023-05-08 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0010_child_gender_alter_app_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
