# Generated by Django 4.2 on 2023-05-09 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0011_child_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
