# Generated by Django 4.2 on 2023-05-14 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0012_child_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='voted_name',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
